# Generated by Django 2.2.6 on 2019-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('completed', models.BooleanField(blank=True)),
                ('completed_time', models.DateTimeField(verbose_name='completed time')),
            ],
        ),
    ]
