# Generated by Django 2.2.6 on 2019-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(blank=True, verbose_name='completed time'),
        ),
    ]
