# Generated by Django 2.2.6 on 2020-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191231_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
