# Generated by Django 2.2.6 on 2019-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191220_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
