# Generated by Django 2.2.6 on 2019-12-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20191220_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
