# Generated by Django 2.2.6 on 2019-12-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
