# Generated by Django 2.2.6 on 2019-12-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tasks',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
