# Generated by Django 2.2.6 on 2019-12-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191225_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
