# Generated by Django 2.2.6 on 2019-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(choices=[('W', 'Web Scraping'), ('F', 'Front_End'), ('B', 'Back_End')], max_length=20)),
                ('Done', models.BooleanField()),
            ],
        ),
    ]
